#!/bin/bash

if [ -f /etc/yum.repos.d/elastix.repo ]; then
   echo "You already have installed Eastix 4"
   rm -f /root/StackScript
   exit
else
   wget --no-check-certificate https://github.com/archer001/TurnC7IntoElx4/archive/master.zip
   unzip master
   chmod +x TurnC7IntoElx4/install.sh
   ./TurnC7IntoElx4/install.sh
fi
